### ISSUE TITLE
How to connect a client-side front-end application like React or Vue.js?

### ISSUE THREAD

**Issue by matheuseabra** [mohammad-hammal/node-restful-starter#1]
Hey congrats for the boilerplate of the node RESTFUL Server. I'm new to server-side development, How could I add a front-end client? Just by installing a package in package.json? Or should I keep the front-end in other repositoyry?

Thank you very much

Matheus

**Comment by mohammad-hammal** [comment]
Oh hello @matheuseabra you can use this package to just get a response when asking for URL on the API 
so you can use React, or any library to get what you want.
For your condition, I think you want to put this with React of Vue, I read good article about this on 
[Medium](https://medium.freecodecamp.org/how-to-make-create-react-app-work-with-a-node-backend-api-7c5c48acb1b0)
